### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by funkymonkeymonk** [SkyJedi/KeyForge-Discord-Data-Bot#1]
Hey,

I was shooting at trying to set up my own copy to run on a Discord server for my Meetup Group but I'm having a bit of trouble. The `fetchImages.js` file hasn't been uploaded and there are no instructions for sourcing the images yourself causing an error loop. Are you able to share the function for populating the data directory? In the medium term is this something that would be better served by making calls to keyforge compendium's API and using the results to link to the CDN for Master Vault?

**Comment by SkyJedi** [comment]
There's a lot of scrapping required for a local instance so I don't have a
easy way of setting it up.  But I do have a bot that can be invited to any
discord instead.

Invite here
https://discordapp.com/oauth2/authorize?client_id=519903193149210626&scope=bot&permissions=280576

If you have more questions let me know.
Invite link to SkyJedi's Bot Emporium!
https://discord.gg/G8au6FH

-SkyJedi
https://www.patreon.com/SkyJedi
